POST http://localhost:8000/api/v1/products/
Content-Type: application/json

{
  "title": "product 7",
  "description": "description 7"
}

###

# создание продукта
POST http://localhost:8000/api/v1/products/
Content-Type: application/json

{
  "title": "Помидор",
  "description": "Лучшие помидоры на рынке"
}

###

# получение продуктов
GET http://localhost:8000/api/v1/products/
Content-Type: application/json

###

# получение
GET http://localhost:8000/api/v1/stocks/
Content-Type: application/json

###

# обновление продукта
PATCH http://localhost:8000/api/v1/products/3/
Content-Type: application/json

{
  "description": "Самые сочные и ароматные помидорки"
}

###

# удаление продукта
DELETE http://localhost:8000/api/v1/products/1/
Content-Type: application/json

###

# поиск продуктов по названию и описанию
GET http://localhost:8000/api/v1/products/?search=Помидор
Content-Type: application/json

###

# создание склада
POST http://localhost:8000/api/v1/stocks/
Content-Type: application/json

{
  "address": "мой адрес 5",
  "positions": [
    {
      "product": 6,
      "quantity": 250,
      "price": 120.50
    },
    {
      "product": 7,
      "quantity": 100,
      "price": 180
    }
  ]
}

###

# обновляем записи на складе
PATCH http://localhost:8000/api/v1/stocks/3/
Content-Type: application/json

{
  "positions": [
    {
      "product": 5,
      "quantity": 100,
      "price": 130.80
    },
    {
      "product": 6,
      "quantity": 243,
      "price": 145
    }
  ]
}

###

# поиск складов, где есть определенный продукт
GET http://localhost:8000/api/v1/stocks/?products=5
Content-Type: application/json
